version: '3.8'

services:
  grt-sys-exchange:
    image: exchange
    environment:
      - DB_HOST=db                  # Hostname do banco (nome do serviço MySQL)
      - DB_USER=exchange_user      # Usuário do banco
      - DB_PASSWORD=exchange_password  # Senha do usuário
      - DB_NAME=exchange_db        # Nome do banco de dados
    depends_on:
      - db
    ports:
      - "8080:80"

  db:
    image: mysql:8.0
    container_name: exchange-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: exchange_db
      MYSQL_USER: exchange_user
      MYSQL_PASSWORD: exchange_password
    ports:
      - "3311:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
